25. Perform Data Cleaning, Data transformation using Python on any data
set.

# Perform Data Cleaning, Data transformation using Python on any data set.

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv("./Datasets/Covid Vaccine Statewise.csv")

df

,Updated On,State,Total Doses Administered,Sessions,Sites,First Dose Administered,Second Dose Administered,Male (Doses Administered),Female (Doses Administered),Transgender (Doses Administered),...,18-44 Years (Doses Administered),45-60 Years (Doses Administered),60+ Years (Doses Administered),18-44 Years(Individuals Vaccinated),45-60 Years(Individuals Vaccinated),60+ Years(Individuals Vaccinated),Male(Individuals Vaccinated),Female(Individuals Vaccinated),Transgender(Individuals Vaccinated),Total Individuals Vaccinated
0,16/01/2021,India,48276.0,3455.0,2957.0,48276.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,23757.0,24517.0,2.0,48276.0
1,17/01/2021,India,58604.0,8532.0,4954.0,58604.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,27348.0,31252.0,4.0,58604.0
2,18/01/2021,India,99449.0,13611.0,6583.0,99449.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,41361.0,58083.0,5.0,99449.0
3,19/01/2021,India,195525.0,17855.0,7951.0,195525.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,81901.0,113613.0,11.0,195525.0
4,20/01/2021,India,251280.0,25472.0,10504.0,251280.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,98111.0,153145.0,24.0,251280.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7840,11/08/2021,West Bengal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7841,12/08/2021,West Bengal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7842,13/08/2021,West Bengal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7843,14/08/2021,West Bengal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7844,15/08/2021,West Bengal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df.head(10)

,Updated On,State,Total Doses Administered,Sessions,Sites,First Dose Administered,Second Dose Administered,Male (Doses Administered),Female (Doses Administered),Transgender (Doses Administered),...,18-44 Years (Doses Administered),45-60 Years (Doses Administered),60+ Years (Doses Administered),18-44 Years(Individuals Vaccinated),45-60 Years(Individuals Vaccinated),60+ Years(Individuals Vaccinated),Male(Individuals Vaccinated),Female(Individuals Vaccinated),Transgender(Individuals Vaccinated),Total Individuals Vaccinated
0,16/01/2021,India,48276.0,3455.0,2957.0,48276.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,23757.0,24517.0,2.0,48276.0
1,17/01/2021,India,58604.0,8532.0,4954.0,58604.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,27348.0,31252.0,4.0,58604.0
2,18/01/2021,India,99449.0,13611.0,6583.0,99449.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,41361.0,58083.0,5.0,99449.0
3,19/01/2021,India,195525.0,17855.0,7951.0,195525.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,81901.0,113613.0,11.0,195525.0
4,20/01/2021,India,251280.0,25472.0,10504.0,251280.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,98111.0,153145.0,24.0,251280.0
5,21/01/2021,India,365965.0,32226.0,12600.0,365965.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,132784.0,233143.0,38.0,365965.0
6,22/01/2021,India,549381.0,36988.0,14115.0,549381.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,193899.0,355402.0,80.0,549381.0
7,23/01/2021,India,759008.0,43076.0,15605.0,759008.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,267856.0,491049.0,103.0,759008.0
8,24/01/2021,India,835058.0,49851.0,18111.0,835058.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,296283.0,538647.0,128.0,835058.0
9,25/01/2021,India,1277104.0,55151.0,19682.0,1277104.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,444137.0,832766.0,201.0,1277104.0

In [5]:
df.columns # printing column values

Index(['Updated On', 'State', 'Total Doses Administered', 'Sessions',
       ' Sites ', 'First Dose Administered', 'Second Dose Administered',
       'Male (Doses Administered)', 'Female (Doses Administered)',
       'Transgender (Doses Administered)', ' Covaxin (Doses Administered)',
       'CoviShield (Doses Administered)', 'Sputnik V (Doses Administered)',
       'AEFI', '18-44 Years (Doses Administered)',
       '45-60 Years (Doses Administered)', '60+ Years (Doses Administered)',
       '18-44 Years(Individuals Vaccinated)',
       '45-60 Years(Individuals Vaccinated)',
       '60+ Years(Individuals Vaccinated)', 'Male(Individuals Vaccinated)',
       'Female(Individuals Vaccinated)', 'Transgender(Individuals Vaccinated)',
       'Total Individuals Vaccinated'],
      dtype='object')

In [6]:
df.describe # describing the dataframe

<bound method NDFrame.describe of       Updated On        State  Total Doses Administered  Sessions   Sites   \
0     16/01/2021        India                   48276.0    3455.0   2957.0
1     17/01/2021        India                   58604.0    8532.0   4954.0
2     18/01/2021        India                   99449.0   13611.0   6583.0
3     19/01/2021        India                  195525.0   17855.0   7951.0
4     20/01/2021        India                  251280.0   25472.0  10504.0
...          ...          ...                       ...       ...      ...
7840  11/08/2021  West Bengal                       NaN       NaN      NaN
7841  12/08/2021  West Bengal                       NaN       NaN      NaN
7842  13/08/2021  West Bengal                       NaN       NaN      NaN
7843  14/08/2021  West Bengal                       NaN       NaN      NaN
7844  15/08/2021  West Bengal                       NaN       NaN      NaN

      First Dose Administered  Second Dose Administered  \
0                     48276.0                       0.0
1                     58604.0                       0.0
2                     99449.0                       0.0
3                    195525.0                       0.0
4                    251280.0                       0.0
...                       ...                       ...
7840                      NaN                       NaN
7841                      NaN                       NaN
7842                      NaN                       NaN
7843                      NaN                       NaN
7844                      NaN                       NaN

      Male (Doses Administered)  Female (Doses Administered)  \
0                           NaN                          NaN
1                           NaN                          NaN
2                           NaN                          NaN
3                           NaN                          NaN
4                           NaN                          NaN
...                         ...                          ...
7840                        NaN                          NaN
7841                        NaN                          NaN
7842                        NaN                          NaN
7843                        NaN                          NaN
7844                        NaN                          NaN

      Transgender (Doses Administered)  ...  18-44 Years (Doses Administered)  \
0                                  NaN  ...                               NaN
1                                  NaN  ...                               NaN
2                                  NaN  ...                               NaN
3                                  NaN  ...                               NaN
4                                  NaN  ...                               NaN
...                                ...  ...                               ...
7840                               NaN  ...                               NaN
7841                               NaN  ...                               NaN
7842                               NaN  ...                               NaN
7843                               NaN  ...                               NaN
7844                               NaN  ...                               NaN

      45-60 Years (Doses Administered)  60+ Years (Doses Administered)  \
0                                  NaN                             NaN
1                                  NaN                             NaN
2                                  NaN                             NaN
3                                  NaN                             NaN
4                                  NaN                             NaN
...                                ...                             ...
7840                               NaN                             NaN
7841                               NaN                             NaN
7842                               NaN                             NaN
7843                               NaN                             NaN
7844                               NaN                             NaN

      18-44 Years(Individuals Vaccinated)  \
0                                     NaN
1                                     NaN
2                                     NaN
3                                     NaN
4                                     NaN
...                                   ...
7840                                  NaN
7841                                  NaN
7842                                  NaN
7843                                  NaN
7844                                  NaN

      45-60 Years(Individuals Vaccinated)  60+ Years(Individuals Vaccinated)  \
0                                     NaN                                NaN
1                                     NaN                                NaN
2                                     NaN                                NaN
3                                     NaN                                NaN
4                                     NaN                                NaN
...                                   ...                                ...
7840                                  NaN                                NaN
7841                                  NaN                                NaN
7842                                  NaN                                NaN
7843                                  NaN                                NaN
7844                                  NaN                                NaN

      Male(Individuals Vaccinated)  Female(Individuals Vaccinated)  \
0                          23757.0                         24517.0
1                          27348.0                         31252.0
2                          41361.0                         58083.0
3                          81901.0                        113613.0
4                          98111.0                        153145.0
...                            ...                             ...
7840                           NaN                             NaN
7841                           NaN                             NaN
7842                           NaN                             NaN
7843                           NaN                             NaN
7844                           NaN                             NaN

      Transgender(Individuals Vaccinated)  Total Individuals Vaccinated
0                                     2.0                       48276.0
1                                     4.0                       58604.0
2                                     5.0                       99449.0
3                                    11.0                      195525.0
4                                    24.0                      251280.0
...                                   ...                           ...
7840                                  NaN                           NaN
7841                                  NaN                           NaN
7842                                  NaN                           NaN
7843                                  NaN                           NaN
7844                                  NaN                           NaN

[7845 rows x 24 columns]>

# Data Cleaning

In [7]:
df.fillna(value=0, inplace=True)
df.head()

# instead of value=0 we can replace it with mean

,Updated On,State,Total Doses Administered,Sessions,Sites,First Dose Administered,Second Dose Administered,Male (Doses Administered),Female (Doses Administered),Transgender (Doses Administered),...,18-44 Years (Doses Administered),45-60 Years (Doses Administered),60+ Years (Doses Administered),18-44 Years(Individuals Vaccinated),45-60 Years(Individuals Vaccinated),60+ Years(Individuals Vaccinated),Male(Individuals Vaccinated),Female(Individuals Vaccinated),Transgender(Individuals Vaccinated),Total Individuals Vaccinated
0,16/01/2021,India,48276.0,3455.0,2957.0,48276.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,23757.0,24517.0,2.0,48276.0
1,17/01/2021,India,58604.0,8532.0,4954.0,58604.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,27348.0,31252.0,4.0,58604.0
2,18/01/2021,India,99449.0,13611.0,6583.0,99449.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,41361.0,58083.0,5.0,99449.0
3,19/01/2021,India,195525.0,17855.0,7951.0,195525.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,81901.0,113613.0,11.0,195525.0
4,20/01/2021,India,251280.0,25472.0,10504.0,251280.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,98111.0,153145.0,24.0,251280.0

In [8]:
df.isnull().sum()

Updated On                             0
State                                  0
Total Doses Administered               0
Sessions                               0
 Sites                                 0
First Dose Administered                0
Second Dose Administered               0
Male (Doses Administered)              0
Female (Doses Administered)            0
Transgender (Doses Administered)       0
 Covaxin (Doses Administered)          0
CoviShield (Doses Administered)        0
Sputnik V (Doses Administered)         0
AEFI                                   0
18-44 Years (Doses Administered)       0
45-60 Years (Doses Administered)       0
60+ Years (Doses Administered)         0
18-44 Years(Individuals Vaccinated)    0
45-60 Years(Individuals Vaccinated)    0
60+ Years(Individuals Vaccinated)      0
Male(Individuals Vaccinated)           0
Female(Individuals Vaccinated)         0
Transgender(Individuals Vaccinated)    0
Total Individuals Vaccinated           0
dtype: int64

In [9]:
df.dtypes

Updated On                              object
State                                   object
Total Doses Administered               float64
Sessions                               float64
 Sites                                 float64
First Dose Administered                float64
Second Dose Administered               float64
Male (Doses Administered)              float64
Female (Doses Administered)            float64
Transgender (Doses Administered)       float64
 Covaxin (Doses Administered)          float64
CoviShield (Doses Administered)        float64
Sputnik V (Doses Administered)         float64
AEFI                                   float64
18-44 Years (Doses Administered)       float64
45-60 Years (Doses Administered)       float64
60+ Years (Doses Administered)         float64
18-44 Years(Individuals Vaccinated)    float64
45-60 Years(Individuals Vaccinated)    float64
60+ Years(Individuals Vaccinated)      float64
Male(Individuals Vaccinated)           float64
Female(Individuals Vaccinated)         float64
Transgender(Individuals Vaccinated)    float64
Total Individuals Vaccinated           float64
dtype: object

# Data Transformation

In [10]:
# changing the dtype of the column

df['Total Doses Administered'] = df['Total Doses Administered'].astype('int64')

df['Sessions'] = df['Sessions'].astype('int64')

df.dtypes

Updated On                              object
State                                   object
Total Doses Administered                 int64
Sessions                                 int64
 Sites                                 float64
First Dose Administered                float64
Second Dose Administered               float64
Male (Doses Administered)              float64
Female (Doses Administered)            float64
Transgender (Doses Administered)       float64
 Covaxin (Doses Administered)          float64
CoviShield (Doses Administered)        float64
Sputnik V (Doses Administered)         float64
AEFI                                   float64
18-44 Years (Doses Administered)       float64
45-60 Years (Doses Administered)       float64
60+ Years (Doses Administered)         float64
18-44 Years(Individuals Vaccinated)    float64
45-60 Years(Individuals Vaccinated)    float64
60+ Years(Individuals Vaccinated)      float64
Male(Individuals Vaccinated)           float64
Female(Individuals Vaccinated)         float64
Transgender(Individuals Vaccinated)    float64
Total Individuals Vaccinated           float64
dtype: object

In [11]:
# Droping the columns

val = df['18-44 Years(Individuals Vaccinated)'].mean()

df['18-44 Years(Individuals Vaccinated)'].fillna(val)

0       0.0
1       0.0
2       0.0
3       0.0
4       0.0
       ...
7840    0.0
7841    0.0
7842    0.0
7843    0.0
7844    0.0
Name: 18-44 Years(Individuals Vaccinated), Length: 7845, dtype: float64